Make entity, migrations and modify relatives backend files
RustineLibre/RustineLibre pull request #42
Opened 2024-07-09 14:08 UTC by Raphael-Marchese

# Description

Please include here a summary of the changes and the related issue.

# Changes

| Q             | A        
|---------------| ---------
| Issue         | #32 ..
| Type          | <ul><li>- [x] Feat</li><li>- [ ] Hotfix</li><li>- [ ] Doc</li><li>- [ ] Refacto</li></ul>
| Break changes |   No

2024-07-17 13:13 UTC, clementtalleu requested changes

2024-07-17 13:13 UTC, clementtalleu commented on api/src/Entity/Repairer.php
> +    'repairerTypes.name' => 'ipartial',
of course, same here

2024-07-17 13:13 UTC, clementtalleu commented on api/src/Entity/Repairer.php
> +    #[ORM\JoinTable(name: 'repairer_repairer_type')]
Do we need the jointTable ? Doctrine could not detect it automatically ? Do not remember if we add this attribute for others manyToMany in the project

2024-07-17 14:08 UTC, Raphael-Marchese commented on api/src/Entity/Repairer.php
> +    'repairerTypes.id' => 'exact',
Yes it works, api-platform allow that, We did it before with the bikeTypeSupported collection

2024-07-22 07:22 UTC, davy-beauzil reviewed
I tested the front end and it seems to work fine, good work 👍 
Just the step, when as user, we take an appointment with a repairer who is an itinerant repairer, we request directly the address of appointment, but I think we should to wait Cécile to know the best solution to implement.
Else, there is a front-end test broken to fix for the CI.

2024-07-24 09:52 UTC, davy-beauzil approved these changes

2024-07-24 10:10 UTC, merged